# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Some Machine Learning Notes
email:
description: > # this means to ignore newlines until "baseurl:"
  This site is a collection of cursory notes for my machine learning study.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://weiliu620.github.io" # the base hostname & protocol for your site
twitter_username: weiliu620
github_username:  weiliu620

# Build settings
markdown: kramdown
